import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "primary-fixed-dim": "#5adace",
        "outline": "#869491",
        "surface-container-highest": "#2d3449",
        "surface-container-low": "#131b2e",
        "on-error": "#690005",
        "error": "#ffb4ab",
        "outline-variant": "#3c4947",
        "on-surface-variant": "#bbc9c7",
        "secondary-fixed": "#d9e3f9",
        "surface-variant": "#2d3449",
        "on-secondary-fixed": "#121c2c",
        "surface-dim": "#0b1326",
        "on-background": "#dae2fd",
        "background": "#0b1326",
        "secondary-container": "#3d4759",
        "on-error-container": "#ffdad6",
        "error-container": "#93000a",
        "on-secondary-fixed-variant": "#3d4759",
        "on-tertiary-container": "#00517a",
        "inverse-on-surface": "#283044",
        "tertiary-fixed": "#cbe6ff",
        "primary-container": "#4fd1c5",
        "on-secondary": "#273141",
        "surface-container-high": "#222a3d",
        "tertiary-fixed-dim": "#8ecdff",
        "primary": "#6feee1",
        "on-tertiary": "#00344f",
        "inverse-primary": "#006a63",
        "on-tertiary-fixed": "#001e30",
        "on-primary-container": "#005750",
        "on-primary-fixed-variant": "#00504a",
        "tertiary": "#b8deff",
        "surface-tint": "#5adace",
        "surface": "#0b1326",
        "on-tertiary-fixed-variant": "#004b71",
        "on-primary-fixed": "#00201d",
        "surface-container-lowest": "#060e20",
        "secondary-fixed-dim": "#bdc7dc",
        "on-primary": "#003733",
        "on-secondary-container": "#abb5cb",
        "tertiary-container": "#78c5ff",
        "surface-container": "#171f33",
        "surface-bright": "#31394d",
        "inverse-surface": "#dae2fd",
        "primary-fixed": "#79f7ea",
        "secondary": "#bdc7dc",
        "on-surface": "#dae2fd",
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px",
      },
      spacing: {
        "margin-safe": "2rem",
        "gutter": "1.5rem",
        "stack-sm": "0.75rem",
        "stack-lg": "3rem",
        "stack-md": "1.5rem",
      },
      fontFamily: {
        "body-md": ["Manrope", "system-ui", "sans-serif"],
        "headline-xl": ["Manrope", "system-ui", "sans-serif"],
        "label-sm": ["Inter", "system-ui", "sans-serif"],
        "headline-lg": ["Manrope", "system-ui", "sans-serif"],
        "headline-lg-mobile": ["Manrope", "system-ui", "sans-serif"],
      },
      fontSize: {
        "body-md": ["18px", { lineHeight: "1.6", letterSpacing: "0.01em", fontWeight: "400" }],
        "headline-xl": ["40px", { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "600" }],
        "label-sm": ["14px", { lineHeight: "1.4", letterSpacing: "0.05em", fontWeight: "500" }],
        "headline-lg": ["32px", { lineHeight: "1.3", letterSpacing: "-0.01em", fontWeight: "500" }],
        "headline-lg-mobile": ["28px", { lineHeight: "1.3", fontWeight: "500" }],
      },
    },
  },
  plugins: [],
};
export default config;
